version: "3.9"
services:

  ch:
    image: "clickhouse/clickhouse-server"
    ports:
      - "38123:8123"
      - "39000:9000"
  backend:
    build: .
    ports:
      - "18000:8000"
    environment:
      - CH_HOST=ch
    links:
      - ch
