from sre_constants import SUCCESS


OPERATIONAL_ERROR_MESSAGE = "operational error when doing operation"
OPERATIONAL_ERROR_CODE = 501 

SUCCESS_EXECUTE_QUERY_MESSAGE = "success execute query"
SUCCESS_EXECUTE_QUERY_CODE = 200

SUCCESS_CREATE_TABLE_MESSAGE = "success create table"
SUCCESS_CREATE_TABLE_CODE = 201

SUCCESS_CREATE_USER_MESSAGE = "success create user"
SUCCESS_CREATE_USER_CODE = 201

ERROR_CREATE_TABLE_MESSAGE = "error when create table"
ERROR_CREATE_TABLE_MESSAGE_CODE = 502

ERROR_CREATE_USER_MESSAGE = "error creating user"
ERROR_CREATE_USER_CODE = 503

ERROR_USER_EXIST_MESSAGE = "user already exists"
ERROR_USER_EXIST_CODE = 504